/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.coderbd.day2;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class EvidenceForm extends javax.swing.JFrame {

    /**
     * Creates new form EvidenceForm
     */
    public EvidenceForm() {
        initComponents();
    }
    
    public static boolean emailValidity(String email){
    int atpos = email.indexOf("@");
    int dotpos= email.indexOf(".");
    
    if(atpos>1 && (dotpos-atpos)>2&& dotpos<email.length()-2){
    return true;
    }else{
    return false;
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNAme = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        rMAle = new javax.swing.JRadioButton();
        btnADD = new javax.swing.JButton();
        rFemale = new javax.swing.JRadioButton();
        chkJava = new javax.swing.JCheckBox();
        chkJS = new javax.swing.JCheckBox();
        chkHTML = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMsg = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDisplay = new javax.swing.JTable();
        btnClearTable = new javax.swing.JButton();
        btnFromFile = new javax.swing.JButton();
        btnClearForm = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cmbRound = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Evidence Form");

        jLabel2.setText("Name");

        jLabel3.setText("Gender");

        jLabel4.setText("Course");

        jLabel5.setText("Comment");

        jLabel11.setText("ID");

        txtId.setText("0");

        buttonGroup1.add(rMAle);
        rMAle.setSelected(true);
        rMAle.setText("Male");

        btnADD.setText("Add");
        btnADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnADDActionPerformed(evt);
            }
        });

        buttonGroup1.add(rFemale);
        rFemale.setText("Female");

        chkJava.setText("Java");

        chkJS.setText("JS");

        chkHTML.setText("HTML");

        txtMsg.setColumns(20);
        txtMsg.setRows(5);
        jScrollPane1.setViewportView(txtMsg);

        tblDisplay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "ID", "Gender", "Course", "Round", "Comment"
            }
        ));
        jScrollPane2.setViewportView(tblDisplay);

        btnClearTable.setText("Clear Table");
        btnClearTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearTableActionPerformed(evt);
            }
        });

        btnFromFile.setText("Read From File");
        btnFromFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFromFileActionPerformed(evt);
            }
        });

        btnClearForm.setText("Clear Form");
        btnClearForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearFormActionPerformed(evt);
            }
        });

        jLabel6.setText("Round");

        cmbRound.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select A Round", "Round 39", "Round 38" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(btnFromFile))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnADD)
                        .addGap(18, 18, 18)
                        .addComponent(btnClearTable)
                        .addGap(18, 18, 18)
                        .addComponent(btnClearForm))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(chkJava)
                                        .addGap(10, 10, 10)
                                        .addComponent(chkJS)
                                        .addGap(18, 18, 18)
                                        .addComponent(chkHTML))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rMAle)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rFemale))
                                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNAme, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbRound, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(234, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(515, 515, 515))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNAme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(rMAle)
                            .addComponent(rFemale))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(chkJava)
                            .addComponent(chkJS)
                            .addComponent(chkHTML))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cmbRound, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnADD)
                                    .addComponent(btnClearTable)
                                    .addComponent(btnClearForm)))
                            .addComponent(jLabel5))
                        .addGap(3, 3, 3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(btnFromFile)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnADDActionPerformed
        // TODO add your handling code here:
        if(txtNAme.getText().trim().length()<3){
            JOptionPane.showMessageDialog(null, "At least 3 charaecters");
        }else if(Integer.parseInt(txtId.getText())<2){
        JOptionPane.showMessageDialog(null, "At least 2 numbers");
        }else if(!rMAle.isSelected() && !rFemale.isSelected()){
        JOptionPane.showMessageDialog(null, "Select your gender");
        }else if(!chkJava.isSelected() && !chkJS.isSelected() && !chkHTML.isSelected()){
        JOptionPane.showMessageDialog(null, "Select your Courses");
        }else if(cmbRound.getItemAt(cmbRound.getSelectedIndex()).equalsIgnoreCase("Select a round")){
        JOptionPane.showMessageDialog(null, "Select your Round");
        }
        
        else{
        String name = txtNAme.getText();
        System.out.println(" Name " + name);
        
        int id = Integer.parseInt(txtId.getText());
        System.out.println(" ID " + id);
        
        String gender=" ";
        if(rMAle.isSelected()){
        gender = rMAle.getText();
        }
        
         if(rFemale.isSelected()){
        gender = rFemale.getText();
        }
         
         System.out.println("Gender " + gender);
         
         String course= " ";
         
         if(chkJava.isSelected()){
         course += chkJava.getText();
         }
         
          if(chkJS.isSelected()){
         course += chkJS.getText();
         }
          
           if(chkHTML.isSelected()){
         course += chkHTML.getText();
         }
           
           System.out.println("Course " + course);
           
           String round = cmbRound.getItemAt(cmbRound.getSelectedIndex());
           System.out.println("Round: " + round);
           
           String comment=txtMsg.getText();
           System.out.println("Comment " + comment);
           
           DefaultTableModel model = (DefaultTableModel)tblDisplay.getModel();
           Object[] row = new Object[6];
           row[0]= name;
           row[1]= id;
           row[2]= gender;
           row[3]= course;
           row[4]= round;
           row[5]= comment;
           model.addRow(row);
           
           Evidence s = new Evidence(name, id, gender, course, round, comment);
           
           List<Evidence> list = new ArrayList<>();
           list.add(s);
           
            try {
                Utility.writeToFile("Tahmina", list);
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_btnADDActionPerformed

    private void btnFromFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFromFileActionPerformed
        // TODO add your handling code here:
        
        /*String Columns []= {"Name", "ID", "Gender", "Course", "Round", "Comment"};
        
        DefaultTableModel tableModel= new DefaultTableModel(0, 8);
        tableModel.setColumnIdentifiers(Columns);
        tblDisplay.setModel(tableModel);
        Utility.displayDatafromTable("Tahmina", tableModel);*/
        
        DefaultTableModel model = (DefaultTableModel) tblDisplay.getModel();
        Utility.displayDatafromTable(JOptionPane.showInputDialog("Enter your file name"), model);
    }//GEN-LAST:event_btnFromFileActionPerformed

    private void btnClearTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearTableActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel model= (DefaultTableModel)tblDisplay.getModel();
        model.setRowCount(0);
    }//GEN-LAST:event_btnClearTableActionPerformed

    private void btnClearFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearFormActionPerformed
        // TODO add your handling code here:
        
        txtNAme.setText(" ");
        txtId.setText(" ");
        buttonGroup1.clearSelection();
        chkJava.setSelected(false);
        chkJS.setSelected(false);
        chkHTML.setSelected(false);
        cmbRound.setSelectedIndex(0);
        txtMsg.setText(" ");
    }//GEN-LAST:event_btnClearFormActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EvidenceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EvidenceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EvidenceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EvidenceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EvidenceForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnADD;
    private javax.swing.JButton btnClearForm;
    private javax.swing.JButton btnClearTable;
    private javax.swing.JButton btnFromFile;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chkHTML;
    private javax.swing.JCheckBox chkJS;
    private javax.swing.JCheckBox chkJava;
    private javax.swing.JComboBox<String> cmbRound;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rFemale;
    private javax.swing.JRadioButton rMAle;
    private javax.swing.JTable tblDisplay;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextArea txtMsg;
    private javax.swing.JTextField txtNAme;
    // End of variables declaration//GEN-END:variables
}
